apiVersion: v1
kind: Pod 
metadata:
  name: "gpu-pod"
  labels:
    app: "caffe"
spec: 
  containers: 
    - 
      name: "gpu-rest-engine"
      image: "beevamariorodriguez/nvidia_caffe_server:nvidia"
      resources: 
        limits: 
          alpha.kubernetes.io/nvidia-gpu: 1
      volumeMounts:
        - mountPath: /usr/local/nvidia
          name: nvidia
  volumes:
  - hostPath:
      path: /usr/local/nvidia
    name: nvidia

